name: Quarkiverse Perform Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.out.outputs.version }}
    steps:
      - name: Output release version
        id: out
        run: echo "version=${DISPATCH_VERSION:-${CALL_VERSION}}" >> $GITHUB_OUTPUT
        env:
          DISPATCH_VERSION: ${{ github.event.inputs.tag}}
          CALL_VERSION: ${{ github.ref_name }}

  perform-release:
    name: Perform Release
    needs: get-version
    uses: quarkiverse/.github/.github/workflows/perform-release.yml@main
    secrets: inherit
    with:
      version: ${{needs.get-version.outputs.version}}
