name: Quarkiverse Perform Release
run-name: Perform ${{env.RELEASE_VERSION}} Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
env:
  RELEASE_VERSION: ${{github.event.inputs.tag || github.ref_name}}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perform-release:
    name: Perform Release
    uses: quarkiverse/.github/.github/workflows/perform-release.yml@main
    secrets: inherit
    with:
      version: ${{env.RELEASE_VERSION}}
