name: Publish Docker
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker Image
        run: |
          docker pull hello-world
          docker tag hello-world:latest ${{github.repository}}:latest

      - name: Save the Docker Image to a file
        run: docker save "${{github.repository}}:latest" -o artifact.tar.gz

      - name: Upload the Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.tar.gz
          retention-days: 1

  publish_image:
    uses: quarkiverse/.github/.github/workflows/deploy-image.yml@main
    needs: build
    secrets: inherit
    with:
      image_name: ${{github.repository}}
      image_tag: latest
