name: Renovate
on:
  workflow_dispatch:
permissions: 
  actions: write
  id-token: write
  contents: write
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.GITHUB_TOKEN }}
          docker-volumes: |
            /tmp:/tmp ;
            /home:/home ;

        env:
          LOG_LEVEL: 'debug'
