name: Test hook
on:
  workflow_dispatch:

jobs:
  asciicinema:
    runs-on: ubuntu-latest
    steps:
      - name: Install Asciicinema
        run: |
          # Update the package list
          sudo apt-get update
          
          # Install Asciicinema
          sudo apt-get install asciinema
          
          # Install the required dependencies
          python3 -m pip install asciinema-automation
