name: Test hook
on:
  workflow_dispatch:

jobs:
  asciicinema:
    runs-on: ubuntu-latest
    steps:
      - name: Update Package list
        run: sudo apt-get update
      - name: Install Asciicinema
        run: sudo apt-get install asciinema
      - name: Install Asciinema-automation
        run: python3 -m pip install asciinema-automation
      - name: Install Asciinema-Agg
        run: cargo install --git https://github.com/asciinema/agg

          
